export interface Exercise {
  id: number
  name: string
  subcategory: string
  description: string
  duration: string
  durationInSeconds: number
  image: string
  equipment?: string
  instructions: string[]
  benefits: string[]
}

export const strengthExercises: Exercise[] = [
  {
    id: 1,
    name: "Push-ups",
    subcategory: "Bodyweight",
    description: "A classic upper body exercise that targets the chest, shoulders, and triceps.",
    duration: "3 sets × 10-15 reps",
    durationInSeconds: 180,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None",
    instructions: [
      "Start in a plank position with hands slightly wider than shoulder-width apart",
      "Lower your body until your chest nearly touches the floor",
      "Push yourself back up to the starting position",
      "Keep your body in a straight line throughout the movement",
    ],
    benefits: [
      "Builds upper body strength",
      "Improves core stability",
      "Can be modified for different fitness levels",
      "Requires no equipment",
    ],
  },
  {
    id: 2,
    name: "Squats",
    subcategory: "Bodyweight",
    description: "A fundamental lower body exercise that targets the quadriceps, hamstrings, and glutes.",
    duration: "3 sets × 12-15 reps",
    durationInSeconds: 180,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None",
    instructions: [
      "Stand with feet shoulder-width apart",
      "Lower your body by bending your knees and pushing your hips back",
      "Keep your chest up and back straight",
      "Lower until thighs are parallel to the ground (or as low as comfortable)",
      "Push through your heels to return to standing position",
    ],
    benefits: [
      "Strengthens lower body muscles",
      "Improves mobility in hips and ankles",
      "Enhances core stability",
      "Functional movement used in everyday activities",
    ],
  },
  {
    id: 3,
    name: "Lunges",
    subcategory: "Bodyweight",
    description: "A unilateral lower body exercise that targets the quadriceps, hamstrings, and glutes.",
    duration: "3 sets × 10 reps each leg",
    durationInSeconds: 180,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None",
    instructions: [
      "Stand with feet hip-width apart",
      "Step forward with one leg and lower your body until both knees are bent at 90 degrees",
      "Keep your front knee aligned with your ankle",
      "Push through the front heel to return to the starting position",
      "Repeat with the other leg",
    ],
    benefits: [
      "Improves balance and stability",
      "Targets muscles in each leg individually",
      "Enhances functional strength",
      "Increases hip flexibility",
    ],
  },
  {
    id: 4,
    name: "Bench Press",
    subcategory: "Weights",
    description: "A compound upper body exercise that primarily targets the chest, shoulders, and triceps.",
    duration: "4 sets × 8-10 reps",
    durationInSeconds: 240,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Barbell, bench",
    instructions: [
      "Lie on a flat bench with feet on the ground",
      "Grip the barbell slightly wider than shoulder-width apart",
      "Lower the bar to your mid-chest",
      "Press the bar back up to the starting position",
      "Keep your wrists straight and elbows at about 45 degrees from your body",
    ],
    benefits: [
      "Builds upper body strength and muscle mass",
      "Develops pushing power",
      "Improves shoulder stability",
      "One of the most effective chest exercises",
    ],
  },
  {
    id: 5,
    name: "Deadlifts",
    subcategory: "Weights",
    description: "A compound full-body exercise that primarily targets the back, glutes, and hamstrings.",
    duration: "4 sets × 6-8 reps",
    durationInSeconds: 240,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Barbell, weight plates",
    instructions: [
      "Stand with feet hip-width apart, barbell over mid-foot",
      "Bend at the hips and knees to grip the bar",
      "Keep your back straight and chest up",
      "Lift the bar by extending your hips and knees",
      "Stand fully upright, then reverse the movement to lower the bar",
    ],
    benefits: [
      "Develops total-body strength",
      "Improves posture and back strength",
      "Increases grip strength",
      "Highly functional movement pattern",
    ],
  },
  {
    id: 6,
    name: "Bicep Curls",
    subcategory: "Weights",
    description: "An isolation exercise that targets the biceps muscles in the front of the upper arm.",
    duration: "3 sets × 12 reps",
    durationInSeconds: 180,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Dumbbells",
    instructions: [
      "Stand with feet shoulder-width apart, holding dumbbells at your sides",
      "Keep your elbows close to your torso",
      "Curl the weights up toward your shoulders",
      "Slowly lower the weights back to the starting position",
      "Maintain control throughout the movement",
    ],
    benefits: [
      "Isolates and strengthens the biceps",
      "Improves arm aesthetics",
      "Enhances grip strength",
      "Can be performed with various equipment (dumbbells, barbell, cables)",
    ],
  },
  {
    id: 7,
    name: "Glute Bridges with Resistance Band",
    subcategory: "Resistance Bands",
    description: "A lower body exercise that targets the glutes and hamstrings using a resistance band.",
    duration: "3 sets × 15 reps",
    durationInSeconds: 180,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Resistance band",
    instructions: [
      "Place a resistance band just above your knees",
      "Lie on your back with knees bent and feet flat on the floor",
      "Push through your heels to lift your hips off the ground",
      "Squeeze your glutes at the top of the movement",
      "Lower your hips back to the starting position",
    ],
    benefits: [
      "Activates and strengthens the glutes",
      "Improves hip stability",
      "Helps correct posture issues",
      "Can be done anywhere with minimal equipment",
    ],
  },
  {
    id: 8,
    name: "Lateral Band Walks",
    subcategory: "Resistance Bands",
    description: "A lateral movement exercise that targets the hip abductors and glutes using a resistance band.",
    duration: "3 sets × 12 steps each direction",
    durationInSeconds: 180,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Resistance band",
    instructions: [
      "Place a resistance band just above your ankles or knees",
      "Stand with feet hip-width apart, slight bend in knees",
      "Step sideways while maintaining tension in the band",
      "Keep your toes pointing forward and core engaged",
      "After completing steps in one direction, repeat in the opposite direction",
    ],
    benefits: [
      "Strengthens hip abductors and glutes",
      "Improves lateral stability",
      "Helps prevent knee injuries",
      "Enhances lower body control and balance",
    ],
  },
]

export const cardioExercises: Exercise[] = [
  {
    id: 9,
    name: "Walking",
    subcategory: "Low-Intensity",
    description: "A low-impact cardio exercise that can be done anywhere and is suitable for all fitness levels.",
    duration: "30-60 minutes",
    durationInSeconds: 2400,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Comfortable shoes",
    instructions: [
      "Stand tall with good posture",
      "Look forward, not down",
      "Swing your arms naturally as you walk",
      "Roll through your foot from heel to toe",
      "Maintain a comfortable pace that slightly elevates your heart rate",
    ],
    benefits: [
      "Improves cardiovascular health",
      "Burns calories and helps with weight management",
      "Low impact on joints",
      "Can be done anywhere with minimal equipment",
      "Great for beginners or active recovery",
    ],
  },
  {
    id: 10,
    name: "Jogging",
    subcategory: "Low-Intensity",
    description: "A moderate-intensity cardio exercise that improves endurance and burns calories.",
    duration: "20-30 minutes",
    durationInSeconds: 1500,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Running shoes",
    instructions: [
      "Maintain good posture with a slight forward lean",
      "Land midfoot, not on your heels",
      "Keep your arms bent at about 90 degrees",
      "Look ahead, not down at your feet",
      "Start with intervals of jogging and walking if you're a beginner",
    ],
    benefits: [
      "Improves cardiovascular fitness",
      "Builds lower body strength",
      "Increases bone density",
      "Releases endorphins (runner's high)",
      "Can be done outdoors or on a treadmill",
    ],
  },
  {
    id: 11,
    name: "Cycling",
    subcategory: "Low-Intensity",
    description: "A low-impact cardio exercise that strengthens the lower body and improves endurance.",
    duration: "30-45 minutes",
    durationInSeconds: 2100,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Bicycle or stationary bike",
    instructions: [
      "Adjust the seat height so your knee is slightly bent at the bottom of the pedal stroke",
      "Keep your back straight and core engaged",
      "Pedal in smooth, circular motions",
      "Maintain a steady cadence",
      "Vary intensity with gears or resistance settings",
    ],
    benefits: [
      "Low impact on joints",
      "Strengthens leg muscles",
      "Improves cardiovascular fitness",
      "Can be adjusted for different intensity levels",
      "Option for outdoor exploration or indoor training",
    ],
  },
  {
    id: 12,
    name: "Sprint Intervals",
    subcategory: "High-Intensity (HIIT)",
    description: "Short bursts of maximum effort followed by recovery periods to improve speed and endurance.",
    duration: "15-20 minutes (including warm-up)",
    durationInSeconds: 1050,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None (outdoor space or treadmill)",
    instructions: [
      "Warm up with 5 minutes of light jogging",
      "Sprint at maximum effort for 20-30 seconds",
      "Recover with walking or light jogging for 60-90 seconds",
      "Repeat for 6-10 rounds",
      "Cool down with 5 minutes of walking",
    ],
    benefits: [
      "Increases anaerobic capacity",
      "Burns calories efficiently",
      "Improves speed and power",
      "Continues to burn calories after workout (EPOC effect)",
      "Time-efficient workout",
    ],
  },
  {
    id: 13,
    name: "Burpees",
    subcategory: "High-Intensity (HIIT)",
    description: "A full-body exercise that combines a squat, push-up, and jump for maximum intensity.",
    duration: "3 sets × 10-15 reps",
    durationInSeconds: 180,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None",
    instructions: [
      "Start in a standing position",
      "Drop into a squat position and place hands on the ground",
      "Kick feet back into a plank position",
      "Perform a push-up (optional)",
      "Jump feet back to squat position",
      "Explosively jump up with arms overhead",
      "Land softly and immediately begin the next rep",
    ],
    benefits: [
      "Works nearly every muscle in the body",
      "Elevates heart rate quickly",
      "Improves strength, endurance, and coordination",
      "Highly efficient for calorie burning",
      "Requires no equipment",
    ],
  },
  {
    id: 14,
    name: "Jumping Jacks",
    subcategory: "High-Intensity (HIIT)",
    description: "A classic cardio exercise that raises your heart rate and works your whole body.",
    duration: "3 sets × 30 seconds",
    durationInSeconds: 180,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None",
    instructions: [
      "Start standing with feet together and arms at your sides",
      "Jump while spreading legs and raising arms overhead",
      "Jump again to return to starting position",
      "Maintain a quick, consistent pace",
      "Keep your core engaged throughout",
    ],
    benefits: [
      "Elevates heart rate quickly",
      "Works upper and lower body simultaneously",
      "Improves coordination",
      "Can be modified for different fitness levels",
      "Requires no equipment and minimal space",
    ],
  },
  {
    id: 15,
    name: "Swimming",
    subcategory: "Sports",
    description: "A full-body, low-impact cardio exercise performed in water.",
    duration: "30-45 minutes",
    durationInSeconds: 2100,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Swimwear, pool access",
    instructions: [
      "Choose a stroke (freestyle, breaststroke, backstroke)",
      "Focus on proper technique and breathing",
      "Start with shorter distances and gradually increase",
      "Consider interval training (e.g., swim hard for one length, recover for the next)",
      "Use kickboards or pull buoys to isolate upper or lower body",
    ],
    benefits: [
      "Zero impact on joints",
      "Works nearly all muscle groups",
      "Improves cardiovascular fitness",
      "Enhances flexibility",
      "Water resistance provides natural strength training",
    ],
  },
  {
    id: 16,
    name: "Basketball",
    subcategory: "Sports",
    description: "A team sport that involves running, jumping, and quick direction changes for a full-body workout.",
    duration: "30-60 minutes",
    durationInSeconds: 2700,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Basketball, court",
    instructions: [
      "Warm up with light jogging and dynamic stretches",
      "Practice dribbling, shooting, and defensive movements",
      "Play full or half-court games",
      "For solo practice, try shooting drills or dribbling exercises",
      "Cool down with light stretching",
    ],
    benefits: [
      "Improves cardiovascular endurance",
      "Develops coordination and agility",
      "Builds teamwork and social skills",
      "Enhances spatial awareness",
      "Provides a fun alternative to traditional cardio",
    ],
  },
]

export const flexibilityExercises: Exercise[] = [
  {
    id: 17,
    name: "Downward Dog",
    subcategory: "Yoga",
    description:
      "A yoga pose that stretches the hamstrings, calves, and shoulders while strengthening the arms and legs.",
    duration: "Hold for 30-60 seconds",
    durationInSeconds: 45,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Yoga mat (optional)",
    instructions: [
      "Start on hands and knees",
      "Lift knees off the floor and push hips up and back",
      "Straighten legs as much as comfortable (slight bend is fine)",
      "Press chest toward thighs",
      "Keep head between arms, looking toward feet",
      "Breathe deeply and hold",
    ],
    benefits: [
      "Stretches entire back of body (hamstrings, calves, spine)",
      "Strengthens arms and shoulders",
      "Improves circulation",
      "Energizes the body",
      "Relieves back pain and tension",
    ],
  },
  {
    id: 18,
    name: "Cobra Stretch",
    subcategory: "Yoga",
    description: "A yoga pose that stretches the chest and strengthens the spine while opening the shoulders.",
    duration: "Hold for 15-30 seconds",
    durationInSeconds: 25,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Yoga mat (optional)",
    instructions: [
      "Lie face down with legs extended and tops of feet on the floor",
      "Place hands under shoulders with elbows close to body",
      "Press into hands to lift chest off the floor",
      "Keep hips and legs on the floor",
      "Draw shoulders back and down",
      "Look straight ahead or slightly upward",
    ],
    benefits: [
      "Stretches chest and abdominal muscles",
      "Strengthens spine and shoulders",
      "Improves posture",
      "Opens the front of the body",
      "Can help relieve lower back pain",
    ],
  },
  {
    id: 19,
    name: "Warrior Pose",
    subcategory: "Yoga",
    description: "A standing yoga pose that strengthens the legs and core while improving balance and focus.",
    duration: "Hold for 30-60 seconds each side",
    durationInSeconds: 90,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Yoga mat (optional)",
    instructions: [
      "Start in a standing position",
      "Step one foot back about 3-4 feet and turn it out at a 45-degree angle",
      "Bend your front knee to 90 degrees, keeping it aligned with your ankle",
      "Keep back leg straight with foot firmly planted",
      "Raise arms overhead or extend them parallel to the floor",
      "Gaze over front hand",
      "Hold, then switch sides",
    ],
    benefits: [
      "Strengthens legs, ankles, and feet",
      "Opens hips and chest",
      "Improves balance and stability",
      "Builds core strength",
      "Enhances focus and concentration",
    ],
  },
  {
    id: 20,
    name: "Dynamic Leg Swings",
    subcategory: "Stretching",
    description:
      "A dynamic stretching exercise for the hips and hamstrings, ideal before running or lower body workouts.",
    duration: "10-15 swings per leg",
    durationInSeconds: 60,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None (wall or chair for support)",
    instructions: [
      "Stand sideways next to a wall or chair for support",
      "Swing one leg forward and backward in a controlled motion",
      "Keep your core engaged and standing leg slightly bent",
      "Gradually increase the height of the swings",
      "Switch to side-to-side swings to target different muscles",
      "Repeat with the other leg",
    ],
    benefits: [
      "Warms up hip flexors and hamstrings",
      "Increases range of motion",
      "Prepares body for activity",
      "Improves hip mobility",
      "Reduces risk of injury during workouts",
    ],
  },
  {
    id: 21,
    name: "Static Hamstring Stretch",
    subcategory: "Stretching",
    description: "A static stretch that targets the hamstrings, ideal for post-workout recovery.",
    duration: "Hold for 20-30 seconds per leg",
    durationInSeconds: 50,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None",
    instructions: [
      "Sit on the floor with one leg extended and the other bent with foot against inner thigh",
      "Reach toward the toes of the extended leg",
      "Keep back straight and bend from the hips",
      "Hold the position without bouncing",
      "Breathe deeply and relax into the stretch",
      "Switch legs and repeat",
    ],
    benefits: [
      "Increases hamstring flexibility",
      "Relieves lower back tension",
      "Improves posture",
      "Enhances athletic performance",
      "Reduces risk of hamstring injuries",
    ],
  },
  {
    id: 22,
    name: "Foam Rolling - Quadriceps",
    subcategory: "Foam Rolling",
    description: "A self-myofascial release technique that helps release tension in the quadriceps muscles.",
    duration: "Roll for 1-2 minutes per leg",
    durationInSeconds: 90,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Foam roller",
    instructions: [
      "Lie face down with a foam roller under the front of one thigh",
      "Support your upper body with your forearms",
      "Roll slowly from hip to knee",
      "Pause on tender spots for 20-30 seconds",
      "Slightly rotate leg inward and outward to target different parts of the muscle",
      "Switch to the other leg",
    ],
    benefits: [
      "Releases muscle knots and tension",
      "Improves blood flow to muscles",
      "Enhances recovery after workouts",
      "Increases range of motion",
      "Reduces muscle soreness",
    ],
  },
  {
    id: 23,
    name: "Foam Rolling - IT Band",
    subcategory: "Foam Rolling",
    description:
      "A self-myofascial release technique that targets the iliotibial (IT) band on the outside of the thigh.",
    duration: "Roll for 1-2 minutes per side",
    durationInSeconds: 90,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Foam roller",
    instructions: [
      "Lie on your side with the foam roller under the outside of your thigh",
      "Support your upper body with your forearm and opposite hand on the floor",
      "Roll slowly from hip to knee",
      "Control pressure by supporting some weight with your arms",
      "Pause on tender spots for 20-30 seconds",
      "Switch to the other side",
    ],
    benefits: [
      "Reduces IT band syndrome symptoms",
      "Relieves knee and hip pain",
      "Improves lateral hip mobility",
      "Enhances recovery for runners and cyclists",
      "Helps prevent overuse injuries",
    ],
  },
]

export const coreExercises: Exercise[] = [
  {
    id: 24,
    name: "Front Plank",
    subcategory: "Planks",
    description: "An isometric core exercise that strengthens the abdominals, back, and shoulders.",
    duration: "Hold for 30-60 seconds",
    durationInSeconds: 45,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None",
    instructions: [
      "Start in a push-up position, then lower onto your forearms",
      "Align elbows directly under shoulders",
      "Keep body in a straight line from head to heels",
      "Engage core by drawing navel toward spine",
      "Keep neck neutral (don't drop or lift head)",
      "Hold the position while breathing normally",
    ],
    benefits: [
      "Strengthens entire core (including deep stabilizing muscles)",
      "Improves posture",
      "Reduces risk of back pain",
      "Enhances athletic performance",
      "Requires no equipment",
    ],
  },
  {
    id: 25,
    name: "Side Plank",
    subcategory: "Planks",
    description: "An isometric exercise that targets the obliques and lateral core muscles.",
    duration: "Hold for 20-40 seconds each side",
    durationInSeconds: 60,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None",
    instructions: [
      "Lie on your side with legs straight",
      "Prop yourself up on your elbow with forearm on the floor",
      "Raise hips so body forms a straight line from head to feet",
      "Stack feet or place top foot in front of bottom foot for more stability",
      "Extend top arm toward ceiling or place hand on hip",
      "Hold position, then switch sides",
    ],
    benefits: [
      "Strengthens obliques and lateral core muscles",
      "Improves lateral stability",
      "Enhances balance",
      "Targets muscles often missed in traditional ab exercises",
      "Can be modified for different fitness levels",
    ],
  },
  {
    id: 26,
    name: "Dynamic Plank with Shoulder Taps",
    subcategory: "Planks",
    description: "A dynamic plank variation that adds shoulder taps to increase difficulty and engage more muscles.",
    duration: "30-45 seconds",
    durationInSeconds: 40,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None",
    instructions: [
      "Start in a high plank position (arms extended)",
      "Ensure body forms a straight line from head to heels",
      "Keeping hips stable, lift one hand to tap the opposite shoulder",
      "Return hand to floor and repeat with other hand",
      "Alternate sides while minimizing hip rotation",
      "Keep core engaged throughout the movement",
    ],
    benefits: [
      "Challenges core stability",
      "Engages shoulders and arms",
      "Improves coordination",
      "Adds anti-rotation component to core training",
      "Increases exercise intensity without equipment",
    ],
  },
  {
    id: 27,
    name: "Russian Twists",
    subcategory: "Core & Stability",
    description: "A rotational exercise that targets the obliques and helps develop core strength.",
    duration: "3 sets × 15-20 reps",
    durationInSeconds: 180,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Dumbbell or medicine ball (optional)",
    instructions: [
      "Sit on the floor with knees bent and feet flat",
      "Lean back slightly to engage core, keeping back straight",
      "Lift feet slightly off the ground for more challenge (optional)",
      "Clasp hands together or hold weight at chest level",
      "Rotate torso to touch hands or weight to the floor on each side",
      "Control the movement and keep shoulders relaxed",
    ],
    benefits: [
      "Strengthens obliques and rotational core muscles",
      "Improves trunk rotation and stability",
      "Enhances sports performance",
      "Can be progressed by adding weight",
      "Works multiple core muscles simultaneously",
    ],
  },
  {
    id: 28,
    name: "Leg Raises",
    subcategory: "Core & Stability",
    description: "A lower abdominal exercise that targets the hip flexors and lower rectus abdominis.",
    duration: "3 sets × 10-15 reps",
    durationInSeconds: 180,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None",
    instructions: [
      "Lie on your back with legs extended and hands at sides or under lower back",
      "Keep lower back pressed into the floor",
      "Raise legs together until perpendicular to the floor",
      "Slowly lower legs back down without touching the floor",
      "Keep core engaged throughout the movement",
      "Avoid using momentum to lift legs",
    ],
    benefits: [
      "Targets lower abdominal muscles",
      "Strengthens hip flexors",
      "Improves core stability",
      "Enhances body control",
      "Can be modified for different fitness levels",
    ],
  },
  {
    id: 29,
    name: "Hanging Knee Tucks",
    subcategory: "Core & Stability",
    description:
      "A challenging core exercise performed while hanging from a bar that targets the lower abs and hip flexors.",
    duration: "3 sets × 8-12 reps",
    durationInSeconds: 180,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Pull-up bar",
    instructions: [
      "Hang from a pull-up bar with arms fully extended",
      "Engage core and avoid swinging",
      "Bend knees and raise them toward chest",
      "Pause briefly at the top of the movement",
      "Lower legs back down with control",
      "Maintain a stable upper body throughout",
    ],
    benefits: [
      "Strengthens core and hip flexors",
      "Improves grip strength",
      "Enhances body control and stability",
      "Targets lower abdominal muscles effectively",
      "Prepares for more advanced hanging exercises",
    ],
  },
  {
    id: 30,
    name: "Mountain Climbers",
    subcategory: "Core & Stability",
    description: "A dynamic exercise that combines core strengthening with cardiovascular benefits.",
    duration: "30-60 seconds",
    durationInSeconds: 45,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None",
    instructions: [
      "Start in a high plank position with arms extended",
      "Keep shoulders over wrists and body in a straight line",
      "Drive one knee toward chest, then quickly switch legs",
      "Maintain a tight core and level hips",
      "Continue alternating legs at a controlled but brisk pace",
      "Breathe rhythmically throughout",
    ],
    benefits: [
      "Strengthens core, shoulders, and hip flexors",
      "Elevates heart rate for cardiovascular benefit",
      "Improves coordination and agility",
      "Burns calories efficiently",
      "Requires no equipment",
    ],
  },
]

export const mindBodyExercises: Exercise[] = [
  {
    id: 31,
    name: "Diaphragmatic Breathing",
    subcategory: "Meditation & Breathing",
    description: "A fundamental breathing technique that promotes relaxation and proper oxygen exchange.",
    duration: "5-10 minutes",
    durationInSeconds: 420,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None",
    instructions: [
      "Sit or lie in a comfortable position",
      "Place one hand on chest and the other on abdomen",
      "Inhale slowly through nose, feeling abdomen expand (not chest)",
      "Exhale slowly through mouth, feeling abdomen contract",
      "Focus on the sensation of breath moving in and out",
      "Continue for several minutes, maintaining a natural rhythm",
    ],
    benefits: [
      "Reduces stress and anxiety",
      "Lowers blood pressure and heart rate",
      "Improves oxygen delivery to tissues",
      "Strengthens diaphragm muscle",
      "Provides foundation for other breathing practices",
    ],
  },
  {
    id: 32,
    name: "Guided Meditation",
    subcategory: "Meditation & Breathing",
    description: "A structured meditation practice led by verbal instructions to promote relaxation and mindfulness.",
    duration: "10-20 minutes",
    durationInSeconds: 900,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Audio guide (optional)",
    instructions: [
      "Find a quiet, comfortable place to sit or lie down",
      "Close eyes or maintain a soft gaze",
      "Follow the guidance provided by instructor or recording",
      "Bring attention back to the guidance when mind wanders",
      "Allow yourself to be fully present in the experience",
      "End the practice gradually, becoming aware of surroundings",
    ],
    benefits: [
      "Reduces stress and anxiety",
      "Improves focus and concentration",
      "Enhances emotional regulation",
      "Promotes better sleep",
      "Accessible for beginners with structured guidance",
    ],
  },
  {
    id: 33,
    name: "Box Breathing",
    subcategory: "Meditation & Breathing",
    description: "A rhythmic breathing technique used to reduce stress and improve concentration.",
    duration: "5 minutes",
    durationInSeconds: 300,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None",
    instructions: [
      "Sit in a comfortable position with back straight",
      "Inhale through nose for a count of 4",
      "Hold breath for a count of 4",
      "Exhale through mouth for a count of 4",
      "Hold empty lungs for a count of 4",
      "Repeat cycle for several minutes",
    ],
    benefits: [
      "Activates parasympathetic nervous system",
      "Reduces stress and anxiety",
      "Improves focus and concentration",
      "Can be done anywhere, anytime",
      "Used by military and first responders for stress management",
    ],
  },
  {
    id: 34,
    name: "Tai Chi - Cloud Hands",
    subcategory: "Tai Chi",
    description: "A flowing movement from Tai Chi that promotes balance, coordination, and relaxation.",
    duration: "Practice for 5-10 minutes",
    durationInSeconds: 420,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None",
    instructions: [
      "Stand with feet shoulder-width apart, knees slightly bent",
      "Begin with hands at waist level, palms facing down",
      "Shift weight to left foot while moving right hand up and left hand down",
      "Turn waist slightly to the right",
      "Shift weight to right foot while moving left hand up and right hand down",
      "Turn waist slightly to the left",
      "Continue this flowing pattern, coordinating breath with movement",
    ],
    benefits: [
      "Improves balance and coordination",
      "Reduces stress and anxiety",
      "Enhances body awareness",
      "Promotes gentle movement for joints",
      "Cultivates mindfulness through movement",
    ],
  },
  {
    id: 35,
    name: "Tai Chi - Standing Meditation",
    subcategory: "Tai Chi",
    description: "A standing posture that develops internal awareness, balance, and strength.",
    duration: "Start with 2-3 minutes, build to 10+ minutes",
    durationInSeconds: 180,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "None",
    instructions: [
      "Stand with feet shoulder-width apart",
      "Slightly bend knees and tuck tailbone",
      "Relax shoulders and let arms hang naturally at sides",
      "Imagine crown of head being gently pulled upward",
      "Breathe naturally and deeply",
      "Focus on sensations in body and maintain stillness",
      "Start with short durations and gradually increase time",
    ],
    benefits: [
      "Develops leg strength and stability",
      "Improves posture and alignment",
      "Cultivates mental focus and patience",
      "Increases body awareness",
      "Serves as foundation for Tai Chi movements",
    ],
  },
  {
    id: 36,
    name: "Pilates - The Hundred",
    subcategory: "Pilates",
    description: "A classic Pilates exercise that strengthens the core while focusing on breath control.",
    duration: "100 beats (approximately 1 minute)",
    durationInSeconds: 60,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Mat",
    instructions: [
      "Lie on back with knees bent at 90 degrees and shins parallel to floor",
      "Lift head and shoulders off mat, reaching arms long by sides",
      "Pump arms up and down in small movements",
      "Inhale for 5 counts, exhale for 5 counts",
      "Continue breathing pattern while pumping arms for 100 beats total",
      "Keep abdominals drawn in and spine pressed to mat",
    ],
    benefits: [
      "Strengthens deep core muscles",
      "Improves breath control",
      "Enhances mind-body connection",
      "Warms up body for other Pilates exercises",
      "Increases circulation",
    ],
  },
  {
    id: 37,
    name: "Pilates - Spine Stretch Forward",
    subcategory: "Pilates",
    description: "A seated Pilates exercise that stretches the spine and hamstrings while engaging the core.",
    duration: "5-8 repetitions",
    durationInSeconds: 120,
    image: "/placeholder.svg?height=300&width=400",
    equipment: "Mat",
    instructions: [
      "Sit tall with legs extended wide, feet flexed",
      "Extend arms forward at shoulder height",
      "Inhale to prepare, growing taller",
      "Exhale as you curl forward, reaching fingertips forward",
      "Roll down through spine one vertebra at a time",
      "Inhale at the bottom of the movement",
      "Exhale as you stack vertebrae back up to sitting tall",
      "Repeat sequence",
    ],
    benefits: [
      "Improves spinal articulation and flexibility",
      "Stretches hamstrings and back muscles",
      "Strengthens core stabilizers",
      "Enhances posture awareness",
      "Promotes proper breathing technique",
    ],
  },
]

